### ISSUE TITLE
Avoid running as root?

### ISSUE THREAD

**Issue by samuell** [lyrasis/docker-blazegraph#5]
Hi folks,

Trying to import this image into minishift gives a warning about this image running as the root user.

See screenshot below:
![selection_372](https://user-images.githubusercontent.com/125003/29873059-4347919e-8d92-11e7-836f-1b782be4ff8d.png)

While I might be digging more into this myself, I wanted to just check with you whether there is any special reason for doing so, or whether you think it would be easy enough to change this?

**Comment by mark-cooper** [comment]
@samuell there is no special reason, and it should be easy to change. A pull request would be very welcome!

**Comment by samuell** [comment]
@mark-cooper Thanks for the quick reply and info! will see what I manage to get working!

**Comment by samuell** [comment]
I'm having some minor success in this branch: https://github.com/pharmbio/docker-blazegraph/tree/feature-nonroot 

... where 
```docker
USER jetty
```
just before the `CMD` part, is the main new thing. 

I can now open the web interface in OpenShift, but getting some errors from jetty/blazegraph about permission errors:

```java
java.io.FileNotFoundException: rules.log (Permission denied)
...
java.io.FileNotFoundException: rules.log (Permission denied)
...
java.io.FileNotFoundException: bigdata.jnl (Permission denied)
```

I'm a bit confused as to where these files are supposed to be located. Any input welcome.

**Comment by mark-cooper** [comment]
@samuell I just did this real quickly: https://github.com/lyrasis/docker-blazegraph/compare/jetty_user?expand=1

Haven't really tested (in particular checking that the examples in the README work), but it builds and appears to run fine.

**Comment by samuell** [comment]
Thanks! Yea, it seems the problems I'm seeing are with OpenShift, which uses random UID's rather than real user names in some places. 

A colleague solved these problems before with some `chmod a+rw <somepath>`, for relevant paths (like `/tmp/jetty`), so perhaps that might work in this case too, for the right paths. Will try ...

**Comment by samuell** [comment]
Found some reference info about the random uid stuff in OpenShift [here](https://docs.openshift.org/latest/creating_images/guidelines.html#use-uid). Not sure if that is perhaps too OpenShift specific for this image though?

**Comment by samuell** [comment]
@mark-cooper Managed to get 2.1.4 to run in openshift ([minishift](https://www.openshift.org/minishift/)) now, with the changes in #6 now!

**Comment by mark-cooper** [comment]
Resolved: https://github.com/lyrasis/docker-blazegraph/pull/6
